services:
  - type: web
    name: supervity-chat-widget-test
    runtime: static
    buildCommand: echo "No build step needed"
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache